---
title: "R Notebook"
output: html_notebook
---

This is my work in progress for parsing MTG Goldfish pages to extract card prices.

```{r}
library(tidyverse,quietly = TRUE)
library(xml2)
library(reticulate)
library(devtools)
library(roxygen2)
options(tibble.print_max = 100, tibble.print_min = 100)
```

```{r}
load_all()
```

```{r}
card_name <- "Snapcaster Mage"
set <- "Innistrad"
plot_card_price_history(card_name, set) %>% plot
```

```{r}
data_dir <- "/home/john/data/mtg/"
write_card_price_history(card_name = card_name, 
                         set = set,
                         directory = data_dir)
```

```{r}
use_python("/usr/bin/python3") #mtgsdk requires python3
mtgsdk <- import("mtgsdk")
```

```{r}
extract_card_info <- function(card) {
  if (!identical(class(card),c("mtgsdk.card.Card", "python.builtin.object")))
    stop("Input is not of the correct class, c(\"mtgsdk.card.Card\", \"python.builtin.object\").")
  list(name     = card$name,
       set_code = card$set,
       set_name = card$set_name)
}
```

```{r, eval=FALSE}
card_dat <- mtgsdk$Card$where(set_name='Innistrad')$all() %>% map_df(extract_card_info)
```

```{r, eval=FALSE}
write_tsv(card_dat, path = "cards.tsv")
```

```{r, eval = FALSE}
basic_lands <- c("Plains", "Island", "Swamp", "Mountain", "Forest")
```

```{r}
df <- card_dat %>% 
  sample_n(30) %>% 
  select(card_name = name, set = set_name) %>% 
  filter(!(card_name %in% basic_lands)) %>%
  mutate(set = case_when(set == "Magic: The Gathering-Commander"  ~ "Commander",
                         set == "Magic: The Gathering-Conspiracy" ~ "Conspiracy",
                         set == "Judge Gift Program"              ~ "Judge Promos",
                         set == "Prerelease Events"               ~ "Prerelease Cards",
                         TRUE                                     ~ set))
```

Flip cards are known broken, e.g. card named Fire Sprites.

```{r}
df[2,] %>% 
  pmap( ~ write_card_price_history(card_name = ..1,
                                   set = ..2,
                                   directory = data_dir))
```











